create database creditRiskAnalysis;
use creditRiskAnalysis;
show tables;
select * from credit_risk_dataset;
select count(*) from credit_risk_dataset;
select count(*) from credit_risk_dataset limit 10;
rename table credit_risk_dataset  to credit;
show tables;

#Q1 WHAT IS THE TOTAL NUMBER OF APPLICANTS:
SELECT COUNT(*) AS TOTAL_APPLICANTS FROM CREDIT;
CREATE VIEW TOTAL_APPLICANTS AS SELECT COUNT(*) FROM CREDIT;
SELECT * FROM TOTAL_APPLICANTS;

#Q2 HOW MANY APPLICANTS ARE DEFAULTED AND HOW MANY HAVE NOT:
SELECT LOAN_STATUS,COUNT(*) AS TOTAL_APPLICANTS FROM CREDIT GROUP BY LOAN_STATUS;
CREATE VIEW DEFAULTED_APPLICANTS_OR_NOT AS SELECT LOAN_STATUS,COUNT(*) AS TOTAL_APPLICANTS FROM CREDIT GROUP BY LOAN_STATUS;
SELECT * FROM DEFAULTED_APPLICANTS_OR_NOT;

#Q3 WHAT IS THE AVERAGE INCOME OF APPLICANTS:
SELECT ROUND(AVG(PERSON_INCOME),2) AS AVG_INCOME FROM CREDIT;
CREATE VIEW AVG_INCOME AS SELECT ROUND(AVG(PERSON_INCOME),2) AS AVG_INCOME FROM CREDIT;
SELECT * FROM AVG_INCOME;

#Q4 HOW MANY APPLICANTS BELONG TO EACH AGE GROUP:
SELECT PERSON_AGE, COUNT(*) AS TOTAL_APPLICANTS FROM CREDIT GROUP BY PERSON_AGE ORDER BY PERSON_AGE;
CREATE VIEW SAME_AGE_GROUP AS SELECT PERSON_AGE, COUNT(*) AS TOTAL_APPLICANTS FROM CREDIT GROUP BY PERSON_AGE ORDER BY PERSON_AGE;
SELECT * FROM SAME_AGE_GROUP;

#Q5 HOW MANY APPLICANTS ARE THERE IN EACH HOME OWNERSHIP CATAGORY:
SELECT PERSON_HOME_OWNERSHIP, COUNT(*) AS TOTAL FROM CREDIT GROUP BY PERSON_HOME_OWNERSHIP ORDER BY TOTAL DESC;
CREATE VIEW OWNERSHIP_CATAGORY AS SELECT PERSON_HOME_OWNERSHIP, COUNT(*) AS TOTAL FROM CREDIT GROUP BY PERSON_HOME_OWNERSHIP ORDER BY TOTAL DESC;
SELECT * FROM OWNERSHIP_CATAGORY;

#Q6 WHICH EMPLOYMENT LENGTH CATAGORY HAS THE HIGHEST NUMBER OF APPLICANTS:
SELECT PERSON_EMP_LENGTH, COUNT(*) AS TOTAL FROM CREDIT GROUP BY PERSON_EMP_LENGTH ORDER BY TOTAL DESC;
CREATE VIEW HIGHEST_NO_APPLICANTS AS SELECT PERSON_EMP_LENGTH, COUNT(*) AS TOTAL FROM CREDIT 
GROUP BY PERSON_EMP_LENGTH ORDER BY TOTAL DESC;
SELECT * FROM HIGHEST_NO_APPLICANTS;

#Q7 HOW MANY LOAN APPLICATIONS ARE THERE FOR EACH LOAN PURPOSE:
SELECT LOAN_INTENT, COUNT(*) AS APPLICATIONS FROM CREDIT GROUP BY LOAN_INTENT ORDER BY APPLICATIONS DESC;
CREATE VIEW LOAN_PURPOSE AS SELECT LOAN_INTENT, COUNT(*) AS APPLICATIONS FROM CREDIT GROUP BY LOAN_INTENT ORDER BY APPLICATIONS DESC;
SELECT * FROM LOAN_PURPOSE;

#Q8 WHAT IS THE AVERAGE LOAN AMPOUNT FOR EACH LOAN PURPOSE:
SELECT LOAN_INTENT, ROUND(AVG(LOAN_AMNT),2) AS AVG_LOAN FROM CREDIT GROUP BY LOAN_INTENT;
CREATE VIEW AVG_LOAN_AMOUNT AS SELECT LOAN_INTENT, ROUND(AVG(LOAN_AMNT),2) AS AVG_LOAN FROM CREDIT GROUP BY LOAN_INTENT;
SELECT * FROM AVG_LOAN_AMOUNT;

#Q9 WHAT ARE THE MINIMUM AND MAXIMUM LOAN AMOUNT:
SELECT MIN(LOAN_AMNT) AS MINIMUM_LOAN, MAX(LOAN_AMNT) AS MAXIMUM_LOAN FROM CREDIT;
CREATE VIEW MIN_MAX_LOAN_AMOUNT AS SELECT MIN(LOAN_AMNT) AS MINIMUM_LOAN, MAX(LOAN_AMNT) AS MAXIMUM_LOAN FROM CREDIT;
SELECT * FROM MIN_MAX_LOAN_AMOUNT;

#Q10 WHAT IS THE AVERAGE INTREST RATE OF LOANS:
SELECT ROUND(AVG(LOAN_INT_RATE),2) AS AVG_INTREST_RATE FROM CREDIT;
CREATE VIEW AVG_INT_RATE AS SELECT ROUND(AVG(LOAN_INT_RATE),2) AS AVG_INTREST_RATE FROM CREDIT;
SELECT * FROM AVG_INT_RATE;

#Q11 WHAT IS THE OVERALL DEFAULT RATE :
SELECT ROUND(SUM(LOAN_STATUS)/COUNT(*)*100,2) AS DEFAULT_RATE FROM CREDIT;
CREATE VIEW OVERALL_DEF_RATE AS SELECT ROUND(SUM(LOAN_STATUS)/COUNT(*)*100,2) AS DEFAULT_RATE FROM CREDIT;
SELECT * FROM OVERALL_DEF_RATE;

#Q12 WHICH LOAN PURPOSE HAS THE HIGHEST NUMBER OF DEFAULTS:
SELECT LOAN_INTENT,COUNT(*) AS DEFAULTS FROM CREDIT WHERE LOAN_STATUS = 1 GROUP BY LOAN_INTENT ORDER BY DEFAULTS DESC;
CREATE VIEW HIGHEST_NO_OF_DEFAULTS AS SELECT LOAN_INTENT,COUNT(*) AS DEFAULTS FROM CREDIT WHERE LOAN_STATUS = 1
GROUP BY LOAN_INTENT ORDER BY DEFAULTS DESC;
SELECT * FROM HIGHEST_NO_OF_DEFAULTS;
 
#Q13 HOW DOES DEFAULT RATE VERT ACROSS INCOME GROUPS:
SELECT CASE WHEN PERSON_INCOME < 50000 THEN 'LOW INCOME' WHEN PERSON_INCOME BETWEEN 50000 AND 100000 THEN 'HIGH INCOME'
END AS INCOME_GROUP, ROUND(AVG(LOAN_STATUS)* 100, 2) AS DEFAULT_RATE FROM CREDIT GROUP BY INCOME_GROUP;
CREATE VIEW DEF_RATE_ACROSS_INCOME_GROUPS AS  SELECT CASE WHEN PERSON_INCOME < 50000 THEN 'LOW INCOME' WHEN PERSON_INCOME BETWEEN 50000 AND 100000 THEN 'HIGH INCOME'
END AS INCOME_GROUP, ROUND(AVG(LOAN_STATUS)* 100, 2) AS DEFAULT_RATE FROM CREDIT GROUP BY INCOME_GROUPS;
SELECT *FROM DEF_RATE_ACROSS_INCOME_GROUPS;

#Q14 RELATIONSHIP BETWEEN CREDIT HISTORY LENGTH AND DEFAULT;
SELECT CB_PERSON_CRED_HIST_LENGTH,ROUND(AVG(LOAN_STATUS)*100,2) AS DEFAULT_RATE FROM CREDIT GROUP BY CB_PERSON_CRED_HIST_LENGTH
ORDER BY CB_PERSON_CRED_HIST_LENGTH;
CREATE VIEW CRED_HIST_LEN_DEF AS SELECT CB_PERSON_CRED_HIST_LENGTH,ROUND(AVG(LOAN_STATUS)*100,2) AS DEFAULT_RATE FROM CREDIT GROUP BY CB_PERSON_CRED_HIST_LENGTH
ORDER BY CB_PERSON_CRED_HIST_LENGTH;
SELECT * FROM CRED_HIST_LEN_DEF;

#Q15 DO HIGHER INTREST LOANS HAVE HIGHER DEFAULTS:
SELECT LOAN_INT_RATE,ROUND(AVG(LOAN_STATUS)*100,2) AS DEFAULT_RATE FROM CREDIT GROUP BY LOAN_INT_RATE ORDER BY LOAN_INT_RATE;
CREATE VIEW HIGHER_DEF AS SELECT LOAN_INT_RATE,ROUND(AVG(LOAN_STATUS)*100,2) AS DEFAULT_RATE FROM CREDIT 
GROUP BY LOAN_INT_RATE ORDER BY LOAN_INT_RATE;
SELECT * FROM HIGHER_DEF;

#Q16 TOP 10 HIGHEST INCOME APPLICANTS:
SELECT * FROM CREDIT ORDER BY PERSON_INCOME DESC LIMIT 10;
CREATE VIEW HIGHEST_INCOME_APPLICANTS AS SELECT * FROM CREDIT ORDER BY PERSON_INCOME DESC LIMIT 10;
SELECT * FROM HIGHEST_INCOME_APPLICANTS;

#Q17 LOAN TO INCOME RATIO:
SELECT LOAN_AMNT,PERSON_INCOME, ROUND(LOAN_AMNT/PERSON_INCOME,4) AS LOAN_INCOME_RATIO FROM CREDIT;
CREATE VIEW INCOME_RATIO AS SELECT LOAN_AMNT,PERSON_INCOME, ROUND(LOAN_AMNT/PERSON_INCOME,4) AS LOAN_INCOME_RATIO FROM CREDIT;
SELECT * FROM INCOME_RATIO;

#Q18 WHICH AGE GROUP HAS THE HIGHEST DEFAULT RATE :
SELECT PERSON_AGE, ROUND(AVG(LOAN_STATUS)*100,2) AS DEFAULT_RATE FROM CREDIT GROUP BY PERSON_AGE ORDER BY DEFAULT_RATE DESC;
CREATE VIEW HIGHEST_DEF_RATE AS SELECT PERSON_AGE, ROUND(AVG(LOAN_STATUS)*100,2) AS DEFAULT_RATE FROM CREDIT
 GROUP BY PERSON_AGE ORDER BY DEFAULT_RATE DESC;
SELECT * FROM HIGHEST_DEF_RATE;

#19 HOW DOES EMPLOYMENT EXPERIENCE AFFECT LOAN STATUS:
SELECT PERSON_EMP_LENGTH, ROUND(AVG(LOAN_STATUS)*100,2) AS DEFAULT_RATE FROM CREDIT GROUP BY PERSON_EMP_LENGTH ORDER BY DEFAULT_RATE DESC;
CREATE VIEW AFFECT_LOAN_STATUS AS SELECT PERSON_EMP_LENGTH, ROUND(AVG(LOAN_STATUS)*100,2) AS DEFAULT_RATE FROM CREDIT 
GROUP BY PERSON_EMP_LENGTH ORDER BY DEFAULT_RATE DESC;
SELECT * FROM AFFECT_LOAN_STATUS;

#Q20 IDENTIFY HIGH RISK APPLICANTS:
SELECT * FROM CREDIT WHERE PERSON_INCOME < 50000 AND LOAN_AMNT > 15000 AND LOAN_INT_RATE > 12 AND CB_PERSON_CRED_HIST_LENGTH < 3;
CREATE VIEW HIGH_RISK_APPLICANTS AS SELECT * FROM CREDIT
 WHERE PERSON_INCOME < 50000 AND LOAN_AMNT > 15000 AND LOAN_INT_RATE > 12 AND CB_PERSON_CRED_HIST_LENGTH < 3;
SELECT * FROM HIGH_RISK_APPLICANTS;

